[package]
name = "angular_proj_statistic"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.9.6"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
